name: Rename Pose Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run rename script
        id: rename
        run: |
          cd hypercat_me
          ./scripts/rename-poses-images.sh
        continue-on-error: true

      - name: Commit files
        if: steps.rename.outcome == 'failure'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add hypercat_me/content/content/poses
          git commit -m "Automated rename of pose images"
          git push
